// Every line the sim writes to the log (round seven, phase 19): say(s, key, args) in sim.js names one here, and
// what it needs. The groundwork for translation: a language is another table with the same keys. What a line
// chooses between (one or many, held or broken) is in its template; a few lines still get words worked out
// where they're said, which a translation will have to bring here first (README, problem 60).
// Each key is the function that says the line and its place there.

export const LINES = {
  'newSeason.1': (a) => `Season 1, day 1. The new moon is ${a.seasonDays} days off. Anyone who dies inside the walls wakes at dusk as a shade.`,
  'newSeason.2': (a) => `${a.kept}, of ${a.keep}, ${(a.length === 1 ? 'is' : 'are')} in the Chapel glass: your own dead, come with you to this keep.`,
  'chapterNews.1': (a) => `Year ${a.k} of the campaign: ${a.name}. ${a.text} The goal: ${a.text2}.`,
  'chapterGoal.1': (a) => a.met ? `${a.name}: the goal is met, to ${a.text}. The keep will tell of it: +${a.goalReward} remembrance.` : `${a.name}: the goal, to ${a.text}, was not met.`,
  'heal.1': (a) => `${a.name} recovered in the infirmary.`,
  'eat.1': 'There is food in the larder again.',
  'eat.2': 'The larder is empty. Everyone works hungry, and the weakest will starve.',
  'study.1': (a) => `The Library has finished ${a.name}${(a.two ? ' II' : '')}: ${a.what}.`,
  'visitorTick.1': (a) => `${(a.inside ? 'In the keep' : 'At the gate')}: ${a.name}.${a.who} ${a.text} unless you answer by ${a.hour}.`,
  'answerVisitor.1': (a) => a.trim,
  'weatherNews.1': (a) => `Rain. The Yard quarries at ${a.round}%, and fire catches and spreads less. ${(a.drownedDue ? `Tonight the Drowned come up out of the moat's twin${a.behind}.` : `The Drowned stay under tonight: ${a.under}.`)}`,
  'weatherNews.2': 'Fog. Tonight the black mirror will show how many come and when, but not their ways.',
  'weatherNews.3': (a) => `Rain is coming tomorrow. Tomorrow night the Drowned come up out of the moat's twin, under the Veil, for the mirrors${(a.behind ? ', behind the line' : '')}.`,
  'weatherNews.4': (a) => `Rain is coming tomorrow. The Drowned will stay under: ${a.under}.`,
  'fire.1': (a) => `Plague: ${a.names} have fallen sick. In a crowded keep it spreads; untreated, it kills within ${a.days} days.`,
  'fire.2': (a) => `${a.name} has fallen sick. Untreated, the sickness kills within ${a.days} days.`,
  'fire.3': (a) => `The crusade is on the road: ${a.count} knights of the Lantern, strength ${a.strength}, at the gate a little after noon. Your defense is ${a.defense}${a.musterNote}. They take no tribute; if they break in, they will smash every mirror they can find.`,
  'fire.4': (a) => `The camp outside stirs: ${a.count} of the Ashen Host will come at the gate, strength ${a.strength}. Your defense is ${a.defense}${a.musterNote}.`,
  'fire.5': (a) => `Raiders on the road: ${a.count} of the Ashen Host, strength ${a.strength}. Your defense is ${a.defense}${a.musterNote}.`,
  'fire.6': (a) => `Word comes from the Lantern Church: its inspector will visit on day ${a.firstInspection}, at noon, to judge how the keep keeps its dead. The less Dread, the better it goes.`,
  'resolveRaid.1': (a) => a.part,
  'resolveRaid.2': (a) => a.held ? `One ${a.one} fell inside the gatehouse.${a.crypt}` : `${a.raiders} ${a.one}${(a.raiders === 1 ? ' was' : 's were')} cut down inside the walls.${a.crypt}`,
  'startAssault.1': (a) => `${a.who}, strength ${a.strength}, against your defense of ${a.def}${a.part}. ${(a.def2 + a.EPS >= a.strength2 ? 'The gate should hold.' : (a.def2 + a.more + a.EPS >= a.strength3 ? 'The gate is giving until they do.' : 'The gate is giving.'))} Pitch, stone and the bell can turn it.`,
  'ladder.1': 'A ladder goes up against the wall, and a gate guard throws it down.',
  'ladder.2': (a) => `A ladder goes up against the wall and stands. Raiders come over it: the Host +${a.ladderHost}.`,
  'endAssault.1': (a) => a.part,
  'endAssault.2': (a) => a.held ? `One ${a.who} fell inside the gatehouse.${a.crypt}` : `${a.raiders} ${a.who}${(a.raiders === 1 ? ' was' : 's were')} cut down inside the walls.${a.crypt}`,
  'crusadeOver.1': (a) => `The crusade breaks on your walls and turns for home. The Lantern Church lifts its embargo and calls its inquisitor away.${a.back}`,
  'crusadeOver.2': (a) => `The crusaders smash ${a.part}${a.part2}. Satisfied, the Lantern Church leaves the keep purged and lifts its embargo. Dread ${a.was} → 0.${a.back}`,
  'inspect.1': (a) => a.read + a.text,
  'kill.1': (a) => `${a.name} ${a.how}.${(a.guided ? ' The Threshold eased the passing.' : '')}${a.grief}`,
  'restFor.1': (a) => `${a.name} is at peace.`,
  'lose.1': (a) => a.text,
  'ignite.1': (a) => `Fire in the ${a.name}! Everyone in it fights it; send the Yard to help, or it will spread and kill.`,
  'burn.1': (a) => `The fire in the ${a.name} is out.`,
  'burn.2': (a) => `The fire spreads from the ${a.name} to the ${a.name2}.`,
  'endDay.1': (a) => `The fire in the ${a.name} burns into the night. Nobody can work there ${a.part}.`,
  'endDay.2': (a) => `${a.name} pockets ${(a.k === 1 ? 'a candle' : `${a.k} candles`)} from the store.`,
  'endDay.3': (a) => a.n ? `Dusk. ${a.n} ${(a.n === 1 ? 'body lies' : 'bodies lie')} in the crypt. Hold funerals or let them wake.` : 'Dusk. Set the candles and post the shades.',
  'gateTired.1': (a) => `${a.name} stood the gate all day, and comes back to the glass the more faded: −${a.loss} memory.`,
  'dayTired.1': (a) => `The dead who helped by day are the more tired for it. Memory: ${a.tired}.`,
  'bury.1': (a) => a.from === 'raider' ? `${a.name} was burned with the Host's dead.` : `${a.name} was laid to rest.`,
  'rise.1': (a) => a.now ? `${a.text} In the eclipse the dead don't wait for dusk.` : a.text,
  'beginEclipse.1': (a) => `The eclipse. The sun goes dark and the Tain wakes with the keep: the dead stand at their posts while the living work${(a.host ? ', and the Host is at the gate' : '')}. ${(a.k === 1 ? 'One Creeper climbs' : `${a.k} Creepers climb`)} before the sun comes back, in ${a.eclipseSecs} seconds. Anyone who dies in the dark wakes at once.`,
  'endEclipse.1': (a) => `The sun comes back. ${(a.burned ? `${(a.burned === 1 ? 'One of the Unlit' : `${a.burned} of the Unlit`)} left in the Tain ${(a.burned === 1 ? 'burns' : 'burn')} away` : 'None of the Unlit are left in the Tain')}${(a.back ? `, and ${(a.back === 1 ? 'a candle' : `${a.back} candles`)} still half whole ${(a.back === 1 ? 'goes' : 'go')} back to the store` : '')}.${a.part}`,
  'startNight.1': (a) => `Night ${a.day}${a.part}. ${a.length} Creepers will come before dawn${(a.drowned && !a.under ? `, and ${(a.drowned === 1 ? 'one of the Drowned' : `${a.drowned} of the Drowned`)} out of the moat` : '')}.`,
  'startNight.2': (a) => `The omen: ${a.name}. ${a.omenText}.`,
  'startNight.3': (a) => `${a.names} ${(a.wraiths === 1 ? 'rises' : 'rise')} as a Wraith in the Waking Room.`,
  'errandTick.1': (a) => `${a.name} is sleepwalking in the Tain, out of the ${a.name2}, making for the Deep. Send a shade, or light their way.`,
  'errandTick.2': (a) => a.saver ? `${a.name} finds ${a.name2} sleepwalking in the Tain and walks them back to bed.` : `${a.name2} wakes in the light in the ${a.where} and finds their way back to bed.`,
  'errandTick.3': (a) => `A ${(a.type === 'wraith' ? 'Wraith' : 'Creeper')} has caught ${a.name}, sleepwalking in the dark of the ${a.where}. Light them or reach them within ${a.max} seconds.`,
  'errandTick.4': (a) => `${a.name} finds an echo in the ${a.name2}, a memory come loose, and takes it in: +${a.echoMemory} memory.`,
  'errandTick.5': (a) => `${a.name} brings back the fallen star from the dark of the ${a.name2}: ${a.starGlass} glass.`,
  'errandTick.6': (a) => `${a.name} brings back a relic from the dark of the ${a.name2}: ${a.relicGlass} glass.`,
  'spawnFoes.1': (a) => `The last great tide rises: ${a.length} Creepers at once, at both rifts. Hold the line until dawn.`,
  'spawnFoes.2': (a) => `A tide rises at the ${a.side} rift${(a.rift !== a.own || a.thinRift === a.rift ? `, for the thinner stair on the ${a.side}` : '')}.`,
  'spawnFoes.3': (a) => `The Unlit are coming up through the Undergate, ${a.tainPlace}.`,
  'spawnFoes.4': (a) => `The Unlit seep up in the ${a.name}. It has no candle.`,
  'spawnFoes.5': (a) => `A Weeper rises ${(a.curse ? "on the hedge-witch's curse" : "for the day's dead")}${a.part}. In the dark there it gives the sleepers nightmares.`,
  'spawnFoes.6': (a) => `A Maw is hauling itself out of the ${a.side} rift. It will go for whatever is worth most for the least fight.`,
  'spawnFoes.7': 'The Hollow rises out of the Deep. It eats the light around it and makes for the mirrors.',
  'riseDrowned.1': (a) => `One of the Drowned comes up out of the moat's twin in the ${a.room}${(a.n > 1 ? ', behind the line' : '')}. It makes for the mirrors, and drags any shade it catches in the dark down into the moat.`,
  'foeTick.1': (a) => a.caught,
  'drownedTick.1': (a) => `${a.caught} Light the spot to make it let go.`,
  'weeperTick.1': (a) => `A Weeper has wept its fill in the ${a.name} and sinks away. Someone asleep above will wake from a nightmare.`,
  'breakRoom.1': (a) => `A Maw has broken the ${a.name}. Nobody works there tonight, and the ${a.name2} is haunted: ${a.hauntCost}.`,
  'comeThrough.1': (a) => `The Maw came through the ${a.name} into the ${a.where}. The Veil holds by a thread; from night ${a.safeUntil}, that would break it and lose the keep.`,
  'comeThrough.2': (a) => `The Maw came through the ${a.name} into the ${a.where}: the Veil cracks, ${a.cracks} of ${a.cracksOf}. A mirror turned to the wall lets nothing through.`,
  'ruinRoom.1': (a) => `Left alone, the Maw has ruined the ${a.name}: tomorrow the ${a.name2}'s workers manage ${a.round}%, and it costs ${a.dreadPerRuin} more Dread at dawn.`,
  'mawTick.1': (a) => `The Maw tears at the candle in the ${a.name}: the room holds while it burns.`,
  'mawTick.2': (a) => `A Maw is tearing down the ${(a.carrier ? 'lantern' : 'candle')} in the ${a.name}.`,
  'mawTick.3': (a) => `A Maw is breaking the ${a.name}. Cut it down, or the ${a.name2} is haunted: ${a.hauntCost}.`,
  'hollowTick.1': 'The Hollow turns from the mirrors toward the lantern.',
  'hollowTick.2': (a) => `The ward on the stair draws on the essence to hold the Hollow back: ${a.part} a second.`,
  'hollowTick.3': (a) => `The essence is spent. The ward holds the Hollow ${a.wardHoldOf} seconds more at most.`,
  'hollowTick.4': 'The Hollow breaks the ward on the stair.',
  'strainCheck.1': (a) => a.part,
  'cross.1': (a) => `More of the tide pours through the mirror in the ${a.where}. The Veil holds, but the sleepers above will pay for it.`,
  'cross.2': (a) => `The Hollow reached the mirror in the ${a.where} and tore through the Veil: ${a.cracks} cracks.`,
  'cross.3': (a) => `${a.who} slipped through the Veil at the mirror in the ${a.where}. The Veil holds by a thread; from night ${a.safeUntil}, that would break it and lose the keep.`,
  'cross.4': (a) => `${a.who} slipped through the Veil at the mirror in the ${a.where}. The Veil cracks: ${a.cracks} of ${a.cracksOf}.`,
  'takeLiving.1': (a) => `It came up into the keep and took ${a.name} from their bed. There is no body to wake.${(a.grieves ? ` ${a.name2} grieves.` : '')}`,
  'foeDown.1': (a) => `A Maw is cut down, and the Hunt pays ${a.bounty} essence.`,
  'foeDown.2': (a) => `${a.name}'s Wraith is cut down and sinks into the Deep for good.`,
  'foeDown.3': (a) => `The Hollow is driven back into the Deep. The keep will tell of it: +${a.reward} remembrance.`,
  'upFromTheDeep.1': (a) => `${a.name} comes back up from the Deep empty-handed. Something caught it down there: −${a.lost} memory.`,
  'upFromTheDeep.2': (a) => `${a.name} comes back up from the Deep with ${a.got} quicksilver.`,
  'fadeAway.1': (a) => a.text,
  'endNight.1': 'Grave-steel from the Cold Forge: tomorrow night every shade fights harder.',
  'endNight.2': (a) => `${a.name} has turned Wraith.`,
  'endNight.3': (a) => `Nightmares: ${a.bad}, in the ${a.where}${(a.spill ? ', from the Unlit that came through the Veil' : '')}. ${a.names} ${(a.bad === 1 ? 'works' : 'work')} at ${a.round}% today.`,
  'toRite.1': 'Dawn. The shades go back into the glass: decide who stays.',
  'release.1': (a) => a.text,
  'beginDay.1': (a) => `${a.name} is banished into the Deep.`,
  'beginDay.2': (a) => `${a.name} is bound to the ${a.name2} and settles as ${a.name3}.`,
  'beginDay.3': (a) => `Dread ${a.from} → ${a.to}.`,
  'beginDay.4': 'Dread has reached its height. The Lantern Church sends an inspector; it arrives at noon.',
  'beginDay.5': 'Word comes from the Lantern Church: an inspector will visit tomorrow at noon and judge how the keep keeps its dead.',
  'beginDay.6': 'No one new can reach the gate through the siege.',
  'beginDay.7': (a) => `${a.when}, day ${a.day}${a.part}.`,
  'beginDay.8': (a) => `Midsummer. At ${a.hour} the sun goes dark for ${a.eclipseSecs} seconds, and the Tain wakes with the keep: the dead at their posts and the Unlit climbing, while the living work and the Host comes to the gate.`,
  'beginDay.9': (a) => `The ${a.names} ${(a.length === 1 ? 'is' : 'are')} haunted${a.till}.${a.half}`,
  'beginDay.10': (a) => `The ${a.names} ${(a.length === 1 ? 'was' : 'were')} ruined in the night: whoever works there manages ${a.round}% until dusk.`,
  'churchDawn.1': (a) => `The crusade comes today: ${a.max} knights of the Lantern, strength ${a.strength}, at the gate a little after noon.`,
  'churchDawn.2': (a) => `The inquisitor will inspect the keep again at noon. The crusade comes ${(a.n === 1 ? 'tomorrow' : `in ${a.n} days`)}; a blessing calls it off.`,
  'churchDawn.3': (a) => a.gone ? 'The inquisitor leaves, and the Lantern Church lifts its embargo.' : 'The Lantern Church lifts its embargo.',
  'churchDawn.4': (a) => `The inquisitor leaves. The silver embargo stands ${(a.n ? `today and ${a.n} more day${(a.n === 1 ? '' : 's')}` : 'through today')}.`,
  'churchDawn.5': 'The inquisitor will inspect the keep again at noon.',
  'siegeDawn.1': 'The Ashen Host breaks camp and marches off. The gate opens.',
  'siegeDawn.2': (a) => `The Ashen Host has made camp outside the walls. For ${a.siegeDays} days the gate is shut: nobody quarries in the Yard, and no one new can come. The guards can sally out to break the camp.`,
  'answerRequests.1': (a) => `${a.name} will stand at the gate today.`,
  'answerRequests.2': (a) => `${a.name} is given a name to keep, and will fade half as fast.`,
  'answerRequests.3': (a) => `${a.name} is remembered: +${a.rememberGain} memory.`,
  'answerRequests.4': (a) => `${a.name}'s request was heard in the Court of Shades. It will wait.`,
  'answerRequests.5': (a) => a.trim,
  'answerRequests.6': (a) => `${a.name}, refused ${(a.refusals === 2 ? 'twice' : `${a.refusals2} times`)}, turns Restless and leaves its mirror for the edge of the Deep.`,
  'newcomer.1': (a) => `${a.name} (${a.age}) arrives at the gate and asks to stay. Assign a job.`,
  'endSeason.1': (a) => `The new moon has passed. Season ${a.season} is over.`,
  'endSeason.2': (a) => a.part,
  'nextSeason.1': (a) => `Season ${a.season} begins with the dawn.${a.turn}${(a.mended ? ' The Veil has knit whole again.' : '')} The Host will come harder, and so will the Unlit.`,
  'yearsTrouble.1': (a) => `${a.name}: ${a.text}.`,
  'generations.1': (a) => `${a.names}.`,
  'byDay.1': (a) => a.part,
  'byDay.2': (a) => `${a.name} will step through the ${a.name2} by day and work in the ${a.name3}.`,
  'raise.1': (a) => `${a.an} rises on top of the keep. By night its twin, the ${a.name}, is the Tain's deepest room.`,
  'raise.2': (a) => `${a.an} rises in the bare hall on floor ${a.n}. By night its twin, the ${a.name}, is ${a.tainPlace}.`,
  'teardown.1': (a) => `The masons tear down the ${a.name}: ${a.back} stone back, and a bare hall.${a.part}`,
  'moveRoom.1': (a) => `The masons swap ${a.named} and ${a.named2}.${a.twin}`,
  'omen.1': (a) => `Tonight's omen, chosen: ${a.name}.`,
  'lantern.1': (a) => `${a.name} sets its lantern down.`,
  'lantern.2': (a) => `${a.name} takes up a lantern: its own light for ${a.lanternWax} seconds, wherever it goes.`,
  'study.2': (a) => `The Library begins ${a.name}${(a.id === 'rites' && a.rank === 1 ? `, for the ${a.name2}` : '')}: ${a.studyLore} lore to go.`,
  'decree.1': (a) => `${a.name} is proclaimed from the Hall, until the season ends: ${a.decreeDoes}. The price: ${a.price}.`,
  'shadeAct.1': (a) => `${a.text} −${a.cost} memory.`,
  'hide.1': (a) => `The ${a.name} is brought out of hiding.`,
  'hide.2': (a) => `The ${a.name} is hidden away${a.part}.`,
  'donate.1': (a) => `A donation of ${a.donation} remembrance to the Lantern Church: it lifts the embargo.`,
  'descend.1': (a) => `${a.name} is called back from the edge of the Deep.`,
  'descend.2': (a) => `${a.name} goes down past the rifts into the Deep, ${a.DEPTHSAt}, to look for quicksilver. It will be back at dawn.`,
  'upgradeMirror.1': (a) => `The ${a.was} is silvered anew as the ${a.name}: room for ${a.cap}.`,
  'build.1': (a) => `The ${a.name} is finished: room for ${a.cap} more ${(a.cap === 1 ? 'shade' : 'shades')}.${a.part}`,
  'hang.1': (a) => `The ${a.before} is hung in the ${a.name}: ${a.twin}.${(a.other ? ` The ${a.name2} that hung there goes where it was${(a.was ? `, as the ${a.name3}` : '')}.` : '')}`,
  'turn.1': (a) => `The ${a.name} is turned back to face the room.${a.part}`,
  'turn.2': (a) => `The ${a.name} is turned to the wall: nothing comes through it.${a.part}`,
  'fightFire.1': (a) => a.part,
  'wardGate.1': (a) => `The gate is warded with essence: defense +${a.ward}.`,
  'payOff.1': (a) => `You pay the Host ${a.food} food and ${a.candles} candles, and they turn back. They'll remember: ${(a.later ? "the season's raids after this one come harder" : "next season's raids come harder")}.`,
  'barStores.1': (a) => `The stores ${(a.state === 'assault' ? 'are' : 'will be')} barred: nobody works the Hearth, the Chandlery or the Glazier while the Host is at the gate, and raiders who break in will carry off half as much.`,
  'pitch.1': (a) => `Burning pitch from the walls: the Host's strength falls to ${a.host}.`,
  'shore.1': (a) => `The masons shore up the gate with stone: it's ${a.round}% whole.`,
  'mend.1': (a) => `Masons mend the gate: it's ${a.round}% whole.`,
  'mend.2': (a) => `Masons mend the ${a.name}: ${(a.broken ? 'the haunting lifts' : 'it can be worked again')}.`,
  'raidBell.1': (a) => `The bell rings: ${a.names} drop their work and run to the walls.`,
  'pursue.1': (a) => `The guards go after the Host and take back ${a.food} food, ${a.glass} glass and ${a.candles} candles.${a.part}`,
  'sally.1': (a) => a.part,
  'vigil.1': (a) => `A vigil in the Chapel eases the keep. Dread ${a.dread} → ${a.dread2}.`,
  'asLastNight.1': (a) => `As last night: ${(a.moved === 1 ? 'one shade' : `${a.moved} shades`)} back at their posts, ${(a.lit === 1 ? 'one candle' : `${a.lit} candles`)} lit${(a.short ? `, and ${(a.short === 1 ? 'one' : a.short)} more wanted, but the store is out` : '')}.${a.part}`,
  'standWard.1': (a) => `A standing ward on ${a.wardPlace}, for ${a.cost} essence: it holds ${(a.n === 1 ? 'tonight' : `every night left this season, ${a.n} of them`)}.`,
  'wardVeil.1': (a) => `The Veil is warded: until the season ends it breaks at ${a.cracksOf} cracks, not ${a.cracksOf2}.`,
  'easeTrouble.1': (a) => `A rite in the Chapel against ${a.charAt}${a.name}: until the season ends it does half what it would.`,
  'break.1': (a) => `The ${a.name} is broken and everyone in it is free. Dread ${a.was} → ${a.dread}. ${a.badLuckDays} days of bad luck follow: sickness comes ${a.part} as often.`,
  'hush.1': (a) => a.on ? 'Hush. The shades go silent; the Unlit pass them by, and all work stops.' : 'The hush ends.',
  'name.1': (a) => `${a.name} is written in the ledger and will fade half as fast.`,
  'closeChapter.1': (a) => `${a.name} closes: ${a.name2}, ${a.text}.`,
  'sealVeil.1': (a) => `The Veil is sealed. ${(a.n ? `${(a.n === 1 ? 'The last shade goes' : (a.n === 2 ? 'Both shades go' : `All ${a.n} shades go`))} free, and` : 'The glass is empty, and')} the Book of the Dead is closed. The keep's story ends here.`,
  'openVeil.1': (a) => `The Veil is opened. ${(a.n ? `${(a.n === 1 ? 'The last shade walks' : `${a.n} shades walk`)} out of the glass and into the keep,` : 'The glass is empty, but')} the living go down into the Tain, and the keep becomes a crossing between the two. The keep's story ends here.`,
  'takeGlass.1': (a) => `You take your own place in the ${a.name}, and a new keeper takes up the keep. ${a.name2} is Loyal, named and Anchored, and weighs ${a.keeperDread} shades' Dread at every rite.`,
};

// A line's words, from its template and what it needs.
export const lineText = (key, args = {}) => {
  const t = LINES[key];
  if (t === undefined) throw new Error(`no line ${key}`);
  return typeof t === 'function' ? t(args) : t;
};
